repo: 'button-styles'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing

html:
  - path: 'index.html'
    outline: false
    has:
      - 'a.btn'
      - check: 'a[class*=" "]'
        message: 'Use multiple classes on the buttons to style them slightly differently from the default button look'
    hasNot:
      - check: 'div[class]'
        message: 'Don’t make any changes to the `<div>`, it’s really just to make each button on a line—not for any styling purposes'
    search:
      - 'Primary button'
      - 'Subtle button'
      - 'Ghost button'
      - 'Warning button'
      - 'button small'
      - 'button big'

css:
  - path: 'css/main.css'
    has:
      - ['.btn', 'display', 'inline-block']
      - ['.btn:hover']
      - ['.btn-small', 'font-size']
      - ['.btn-big', 'font-size']
      - ['.btn-subtle']
      - ['.btn-subtle:hover']
      - ['.btn-ghost']
      - ['.btn-ghost:hover']
      - ['.btn-warning']
      - ['.btn-warning:hover']
      - ['div', ['padding', 'text-align']]
    has_not:
      - check: 'a'
        message: 'The `<a>` tag should not be targeted directly because we don’t want to affect *every single link* — the `.btn` class should have all the styles necessary for a button'
      - ['.btn-small', ['padding', 'display', 'background-color', 'border-radius', 'border', 'color', 'text-decoration']]
      - ['.btn-big', ['padding', 'display', 'background-color', 'border-radius', 'border', 'color', 'text-decoration']]
      - ['.btn-subtle', ['padding', 'display', 'border-radius', 'border', 'text-decoration', 'font-size']]
      - ['.btn-ghost', ['padding', 'display', 'border-radius', 'border', 'text-decoration', 'font-size']]
      - ['.btn-warning', ['padding', 'display', 'border-radius', 'border', 'text-decoration', 'font-size']]
      - check: ['div', ['display', 'border', 'border-color', 'border-radius', 'font-size', 'border-width', 'border-style', 'color', 'background-color']]
        message: 'Don’t make any changes to the `<div>` in the CSS, it should have `padding` & `text-align` only'
    search_not:
      - '\.btn-subtle-small'
      - '\.btn-small-subtle'
      - '\.btn-big-subtle'
      - '\.btn-subtle-big'
      - '\.btn-ghost-small'
      - '\.btn-small-ghost'
      - '\.btn-big-ghost'
      - '\.btn-ghost-big'
      - '\.btn-warning-small'
      - '\.btn-small-warning'
      - '\.btn-big-warning'
      - '\.btn-warning-big'

screenshots:
  - path: 'index.html'
    sizes: [400]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('div:first-child a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the first button doesn’t change when hovered')
          pass();
        });

      - |
        let link = $('div:nth-child(2) a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the second button doesn’t change when hovered')
          pass();
        });

      - |
        let link = $('div:nth-child(3) a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the third button doesn’t change when hovered')
          pass();
        });
